# Generated by Django 3.1.5 on 2021-01-26 03:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenPersonalInfo',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=250, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('Non-binary', 'Non-binary')], max_length=150)),
                ('address', models.CharField(max_length=400)),
                ('civil_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widow')], max_length=15)),
                ('occupation', models.CharField(max_length=150)),
            ],
        ),
    ]
