# Generated by Django 3.1.5 on 2021-01-26 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citizenpersonalinfo',
            options={'verbose_name': 'Citizen Personal Information'},
        ),
    ]
