# Generated by Django 3.1.5 on 2021-01-26 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_medicalhistory_medicalrecord_treatmetreceive'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=None, default='default.jpg', upload_to='profile')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_profile', to='core_api.citizenpersonalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CitizenContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(help_text='include the prefix', max_length=20, verbose_name='contact number')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_contact', to='core_api.citizenpersonalinfo')),
            ],
        ),
    ]
