# Generated by Django 3.1.5 on 2021-01-26 10:26

from django.db import migrations
# from .models import MedicalHistory, TreatmentReceive


def apply_user(apps, schema_editor):
    citizen = apps.get_model('core_api', 'CitizenProfile')
    medical_history = apps.get_model('core_api', 'MedicalHistory')
    treatment_receive = apps.get_model('core_api', 'TreatmentReceive')

    for medical in medical_history.objects.all():
        medical_history.citizen = citizen.objects.get(first_name='John')
        medical_history.save()

    for treatment in treatment_receive.objects.all():
        treatment_receive.citizen = citizen.objects.get(first_name='John')
        treatment_receive.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0004_citizencontactinfo_citizenprofile'),
    ]

    operations = [
        migrations.RunPython(apply_user)
    ]
