# Generated by Django 3.1.5 on 2021-01-26 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0004_citizencontactinfo_citizenprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_interacted', models.CharField(blank=True, max_length=250)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_trace', to='core_api.citizenpersonalinfo')),
            ],
            options={
                'verbose_name_plural': 'Contact Trace',
            },
        ),
        migrations.CreateModel(
            name='CovidStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covid_case', models.CharField(blank=True, choices=[('Asymptomatic', 'Asymptomatic'), ('Symptomatic', 'Symptomatic')], max_length=150)),
                ('days_of_quarantine', models.CharField(blank=True, choices=[('7', '7 days'), ('14', '14 days'), ('24', '24 days')], max_length=150)),
                ('status', models.CharField(blank=True, choices=[('N', 'Negative'), ('P', 'Positive'), ('PUI', 'Patience Under Investigation')], max_length=150)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_status', to='core_api.citizenpersonalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TravelHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_history', models.CharField(blank=True, max_length=250)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_history', to='core_api.citizenpersonalinfo')),
            ],
            options={
                'verbose_name_plural': 'Travel Histories',
            },
        ),
        migrations.RemoveField(
            model_name='treatmentreceive',
            name='medical_rec',
        ),
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
        migrations.DeleteModel(
            name='TreatmentReceive',
        ),
    ]
