# Generated by Django 3.1.5 on 2021-01-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0006_medicalhistory_treatmentreceive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citizencontactinfo',
            options={'verbose_name': 'Citizen Contact Information'},
        ),
        migrations.AlterModelOptions(
            name='covidstatus',
            options={'verbose_name_plural': 'Covid Status'},
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='temperature',
            field=models.FloatField(help_text='in celsius'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='weight',
            field=models.FloatField(help_text='in kg'),
        ),
    ]
