# Generated by Django 3.1.5 on 2021-02-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0007_auto_20210128_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('Negative', 'Negative'), ('Positive', 'Positive'), ('PUI', 'Patience Under Investigation')], max_length=150),
        ),
    ]
