# Generated by Django 3.1.5 on 2021-02-04 04:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0008_auto_20210204_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='last_checkup',
            field=models.DateField(default=datetime.datetime(2021, 2, 4, 4, 27, 5, 939107, tzinfo=utc)),
        ),
    ]
